-- Presentation booking database setup for Supabase project DJI
-- 11 groups, 11 x 20-minute slots, Singapore time.
-- Stores only student-entered name + group number.

create extension if not exists pgcrypto;

create table if not exists public.presentation_slots (
  id bigint generated by default as identity primary key,
  start_at timestamptz not null unique,
  end_at timestamptz not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  constraint presentation_slots_valid_time check (end_at > start_at)
);

create table if not exists public.presentation_bookings (
  id uuid primary key default gen_random_uuid(),
  slot_id bigint not null unique references public.presentation_slots(id) on delete restrict,
  group_no smallint not null unique,
  student_name text not null,
  created_at timestamptz not null default now(),
  constraint presentation_bookings_group_range check (group_no between 1 and 11),
  constraint presentation_bookings_name_length check (char_length(trim(student_name)) between 2 and 120)
);

create index if not exists presentation_slots_start_at_idx
  on public.presentation_slots(start_at);

alter table public.presentation_slots enable row level security;
alter table public.presentation_bookings enable row level security;

-- Browser users cannot access the underlying tables directly.
revoke all on table public.presentation_slots from anon, authenticated;
revoke all on table public.presentation_bookings from anon, authenticated;

-- Keep exactly these 11 active slots.
update public.presentation_slots set is_active = false;

insert into public.presentation_slots (start_at, end_at, is_active) values
  ('2026-09-07 13:00:00+08', '2026-09-07 13:20:00+08', true),
  ('2026-09-07 13:20:00+08', '2026-09-07 13:40:00+08', true),
  ('2026-09-07 13:40:00+08', '2026-09-07 14:00:00+08', true),
  ('2026-09-07 14:00:00+08', '2026-09-07 14:20:00+08', true),
  ('2026-09-07 14:20:00+08', '2026-09-07 14:40:00+08', true),
  ('2026-09-07 14:40:00+08', '2026-09-07 15:00:00+08', true),
  ('2026-09-07 15:00:00+08', '2026-09-07 15:20:00+08', true),
  ('2026-09-08 13:00:00+08', '2026-09-08 13:20:00+08', true),
  ('2026-09-08 13:20:00+08', '2026-09-08 13:40:00+08', true),
  ('2026-09-08 13:40:00+08', '2026-09-08 14:00:00+08', true),
  ('2026-09-08 14:00:00+08', '2026-09-08 14:20:00+08', true)
on conflict (start_at) do update set
  end_at = excluded.end_at,
  is_active = true;

create or replace function public.get_available_presentation_slots()
returns table (
  id bigint,
  start_at timestamptz,
  end_at timestamptz
)
language sql
security definer
set search_path = public, pg_temp
as $$
  select s.id, s.start_at, s.end_at
  from public.presentation_slots s
  where s.is_active = true
    and not exists (
      select 1
      from public.presentation_bookings b
      where b.slot_id = s.id
    )
  order by s.start_at;
$$;

create or replace function public.book_presentation_slot(
  p_slot_id bigint,
  p_group_no smallint,
  p_student_name text
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_name text := trim(p_student_name);
  v_start timestamptz;
  v_end timestamptz;
begin
  if p_group_no is null or p_group_no < 1 or p_group_no > 11 then
    return jsonb_build_object(
      'ok', false,
      'code', 'INVALID_GROUP',
      'message', 'Group number must be between 1 and 11.'
    );
  end if;

  if v_name is null or char_length(v_name) < 2 or char_length(v_name) > 120 then
    return jsonb_build_object(
      'ok', false,
      'code', 'INVALID_NAME',
      'message', 'Please enter your name.'
    );
  end if;

  select s.start_at, s.end_at
  into v_start, v_end
  from public.presentation_slots s
  where s.id = p_slot_id
    and s.is_active = true;

  if not found then
    return jsonb_build_object(
      'ok', false,
      'code', 'INVALID_SLOT',
      'message', 'This slot is not available.'
    );
  end if;

  begin
    insert into public.presentation_bookings (slot_id, group_no, student_name)
    values (p_slot_id, p_group_no, v_name);
  exception
    when unique_violation then
      if exists (
        select 1
        from public.presentation_bookings
        where group_no = p_group_no
      ) then
        return jsonb_build_object(
          'ok', false,
          'code', 'GROUP_ALREADY_BOOKED',
          'message', 'Your group has already booked a presentation slot.'
        );
      else
        return jsonb_build_object(
          'ok', false,
          'code', 'SLOT_TAKEN',
          'message', 'That slot was just taken. Please choose another slot.'
        );
      end if;
  end;

  return jsonb_build_object(
    'ok', true,
    'code', 'BOOKED',
    'message', 'Presentation slot booked successfully.',
    'group_no', p_group_no,
    'student_name', v_name,
    'start_at', v_start,
    'end_at', v_end
  );
end;
$$;

-- Functions are the only public API surface.
revoke all on function public.get_available_presentation_slots() from public;
revoke all on function public.book_presentation_slot(bigint, smallint, text) from public;

grant execute on function public.get_available_presentation_slots() to anon, authenticated;
grant execute on function public.book_presentation_slot(bigint, smallint, text) to anon, authenticated;

-- Helpful verification queries:
-- select * from public.get_available_presentation_slots();
-- select count(*) as active_slots from public.presentation_slots where is_active = true;
